blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/posts/', PostListView.as_view(), name='posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post'),
    path('create/', PostCreateView.as_view(), name='create_post'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete_post')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name='заголовок')
    slug = models.CharField(max_length=100)
    content = models.TextField(verbose_name='содержимое статьи')
    preview = models.ImageField(upload_to='post/photo', verbose_name='превью', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Post


class PostListView(ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PostCreateView(CreateView):
    model = Post
    fields = ('title', 'content', 'preview', 'is_published')
    success_url = reverse_lazy('blog:posts')

    def form_valid(self, form):
        if form.is_valid():
            post = form.save()
            post.slug = slugify(post.title)
            post.save()

        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ('title', 'content', 'preview', 'is_published')

    def get_success_url(self):
        return reverse('blog:post', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            post = form.save()
            post.slug = slugify(post.title)
            post.save()

        return super().form_valid(form)


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:posts')

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/post_list.html' %}
{% block post %}
    <div class="col-10">
        <div class="row">
            <div class="col-2">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы хотите удалить "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <div class="btn btn-warning">
                                <a href="{% url 'blog:posts' %}">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/post_list.html' %}
{% load static %}
{% block post %}

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading"> {{ object.title }} </h1>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img src="/media/{{ object.preview }}" />
                        <div class="card-body">
                            <p class="card-text">{{ object.title }}</p>
                            <p class="card-text">{{ object.content }}</p>
                            <p class="card-text">{{ object.created_at }}</p>
                            <p class="card-text"> Количество просмотров: {{ object.views_count }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'blog:posts' %}" class="btn">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/post_list.html' %}
{% block post %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Применить</button>
                            <div class="btn btn-warning">
                                <a href="{% url 'blog:posts' %}">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Блог </title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css'%}" rel="stylesheet">
</head>

<body>
{% include 'includes/nav_bar.html' %}

<main role="main">
    {% block post %}

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading"> БЛОГ </h1>
        </div>
    </section>

    <div class="album py-5 bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-5">
                    <a class="btn btn-outline-primary" href="{% url 'blog:create_post' %}">Добавить пост</a>
                </div>
                {% for object in object_list %}
                <div class="col-md-6">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2> {{ object.title }} </h2>
                            <div class="btn-group-center">
                                <a href="{% url 'blog:post' object.pk %}" class="btn btn-primary">Просмотреть</a>
                                <a href="{% url 'blog:update_post' object.pk %}" class="btn btn-warning">Редактировать</a>
                                <a href="{% url 'blog:delete_post' object.pk %}" class="btn btn-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}
</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y'%} </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>