blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/posts/', PostListView.as_view(), name='posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post'),
    path('create/', PostCreateView.as_view(), name='create_post'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete_post')
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import ContactsView, ProductDetailView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='products'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование категории')
    description = models.CharField(max_length=100, verbose_name='описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='название продукта')
    description = models.TextField(verbose_name='описание')
    category_name = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='категория', null=True, blank=True, related_name='products')
    image = models.ImageField(upload_to='product/photo', verbose_name='фото', null=True, blank=True)
    price = models.IntegerField(verbose_name='цена')
    created_at = models.DateField(verbose_name='дата создания', null=True, blank=True)
    updated_at = models.DateField(verbose_name='дата изменения', null=True, blank=True)

    def __str__(self):
        return (f'Категория: {self.category_name}, наименование: {self.title}, цена: {self.price}руб., описание: {self.description}.')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, verbose_name='продукт', related_name='versions')
    num_of_version = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=150, verbose_name='название версии')
    is_active_version = models.BooleanField(default=True, verbose_name='теущая версия')

    def __str__(self):
        return f'{self.version_name} - {self.num_of_version}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'category_name', 'image', 'price',)

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in bad_words:
            if word in cleaned_data:
                raise forms.ValidationError('Ошибка! название не должно содержать запрещённых слов!')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in bad_words:
            if word in cleaned_data:
                raise forms.ValidationError('Ошибка! описание не должно содержать запрещённых слов!')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ("__all__")

catalog/views.py
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


class ProductListView(ListView):
    Model = Product

    def get_queryset(self):
        return Product.objects.order_by('id')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['version_list'] = Version.objects.all()
        return context_data



class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:products', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{title}}</title>



    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css'%}" rel="stylesheet">
</head>

<body>
{% include 'includes/nav_bar.html' %}

{% block home %}
{% endblock %}
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y'%} </p>
    </div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Контакты </title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css'%}" rel="stylesheet">
</head>

<body>

{% include 'includes/nav_bar.html' %}

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading"> Контакты </h1>
        </div>
    </section>

    <div class="album py-5 bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2>Связаться с нами</h2>
                            <p class="card-text">
                                Офис Москва +74956753434<br>
                                Офис Новосибирск +73831231414
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2>Вы можете написать нам</h2>
                            <form method="post">
                                {% csrf_token %}
                                <input class="form-control mb-2" name="name" />
                                <input class="form-control mb-2" name="email" />
                                <textarea class="form-control mb-2" name="message"></textarea>
                                <button type="submit" class="btn btn-primary form-control">Отпраить</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y'%} </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block home %}
<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{title}}</h1>
        </div>
    </section>
    {% block content %}
    <div class="album py-5 bg-light text-center">
        <div class="container">
            <div class="row">
                {% for object in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <p class="card-text">{{ object.title }}</p>
                            <p class="card-text">{{ short_description }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'catalog:products' object.pk %}" class="btn">View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

</main>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/product_list.html' %}
{% load tags %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-title">
                        Удаление
                    </div>
                    <img src="{{ product.image | img }}">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы хотите удалить "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <div class="btn btn-warning">
                                <a href="{% url 'catalog:home' %}">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/product_list.html' %}
{% load tags %}
{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading"> {{ object.title.capitalize }} </h1>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4 box-shadow">
                    <img src="{{ product.image | img }}">
                    <div class="card-body">
                        <p class="card-text">Категория: {{ object.category_name }}</p>
                        <p class="card-text">Наименование: {{ object.title }}</p>
                        <p class="card-text">Цена: {{ object.price }}руб.</p>
                        <p class="card-text">Описание: {{ object.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'catalog:home' %}" class="btn btn-warning">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block home %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    {% if object %}
                    Изменить продукт
                    {% else %}
                    Добавление продукта
                    {% endif %}
                </h2>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    Добавить версию
                </h2>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                {% endfor %}
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block home %}
<main role="main">
    {% block content %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading"> Главная </h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <a href="{% url 'catalog:create' %}" class="btn btn-primary form-control">Добавить продукт</a>
        <div class="container">
            <div class="row">
                {% for object in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <p class="card-text">{{ object.title.capitalize }}</p>
                            <p class="card-text">{{ short_description }}</p>
                            {% if object.versions.all %}
                            {% for version in object.versions.all %}
                                {% if version.is_active_version %}
                                <p class="card-text">Версия: {{ version.version_name }}-{{ version.num_of_version }}</p>
                                {% else %}
                                <p class="card-text">Нет текущей версии</p>
                                {% endif %}
                            {% endfor %}
                            {% else %}
                            <p class="card-text">Нет текущей версии</p>
                            {% endif %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'catalog:products' object.pk %}" class="btn btn-success">Подробнее</a>
                                    <a href="{% url 'catalog:update' object.pk %}" class="btn btn-warning">Изменить</a>
                                    <a href="{% url 'catalog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

</main>
{% endblock %}